# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.13

jobs:
  build:
    executor: node

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn build-storybook

      - save_cache:
          paths:
            - storybook-static
          key: v1-storybook-{{ .Branch }}-{{ .Revision }}

  deploy:
    executor: node

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-storybook-{{ .Branch }}-{{ .Revision }}

      - run: yarn global add netlify-cli
      - run: echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
      - run: netlify deploy --prod --dir=./storybook-static --site=$NETLIFY_SITE_ID

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
